/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2015-12-10 03:55:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.ArrayList;
import java.text.DecimalFormat;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("  \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Turnout</title>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <!-- Bootstrap -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css\">\r\n");
      out.write("  \t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js\"></script>\r\n");
      out.write(" \t<script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write(" <!-- Style Sheet-->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"MainStyle.css\">\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- \r\n");
      out.write("\t\tTO DO LIST \r\n");
      out.write("\r\n");
      out.write("done\t1) teacher link to register<br>\t\t\t\t\t\t\t\r\n");
      out.write("done\t2) student link to register<br>\r\n");
      out.write("done\t3) teacher link to add class<br>\r\n");
      out.write("done\t4) student link to register to class<br>\r\n");
      out.write("\t\t5) teacher link to view attendance<br>\r\n");
      out.write("\t\t6) student link to view all of their attendance<br>\r\n");
      out.write("\t\t7) teacher link to add class + attendance\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tdo if time permits \r\n");
      out.write("\t\t~ teacher link to edit students\r\n");
      out.write("\t\r\n");
      out.write("Session variable map\r\n");
      out.write("\tuser -> indicates the type of user {student,teacher}\r\n");
      out.write("\tusername -> indicated the logged in email(teacher) or the USN(student) {email,USN}\r\n");
      out.write("\tid ->  indicated the index to table {t_id ,s_id}\r\n");
      out.write("\r\n");
      out.write("-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-inverse\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <div class=\"navbar-header\">\r\n");
      out.write("      <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#myNavbar\">\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>                        \r\n");
      out.write("      </button>\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"index.jsp\"><span class=\"glyphicon glyphicon-education\"></span><b>&nbspTurnout</b></a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"myNavbar\">\r\n");
      out.write("      <ul class=\"nav navbar-nav\">\r\n");
      out.write("        <li class=\"active\"><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("        <li><a href=\"about.jsp\">About</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("      <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("        <li><a href=\"signup.jsp\"><span class=\"glyphicon glyphicon-user\"></span> Sign Up</a></li>\r\n");
      out.write("        ");
	if(session.getAttribute("ID")==null)
        		{	
        			
      out.write("\r\n");
      out.write("        \t\t\t\t<li><a href=\"login.jsp\"><span class=\"glyphicon glyphicon-log-in\"></span> Login</a></li>\r\n");
      out.write("        \t\t\t");
 
        		}
       		else
       		{
       			
      out.write("\r\n");
      out.write("\t\t\t\t<li><a href=\"logout.jsp\"><span class=\"glyphicon glyphicon-log-in\"></span> Logout</a></li>\r\n");
      out.write("\t\t\t\t");
 
       		}
        
      out.write("\r\n");
      out.write("        \r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<div class=\"container\">\t\r\n");

		// checks if logged in , if not redirect to login
		if(session.getAttribute("ID")!=null)
		{
			//getting the session variables(session var map given at the top)
			String user = (String) session.getAttribute("USER");
			String username =(String)  session.getAttribute("USERNAME");
			String id = (String) session.getAttribute("ID");
			
			// JDBC driver name and database URL
  		    String JDBC_DRIVER = "com.mysql.jdbc.Driver";  
  		    String DB_URL = "jdbc:mysql://www.virtualhighs.com:3306/turnout";

  		   //  Database credentials
  		    String USER = "ateam";
  		    String PASS = "1191995";

  		    Connection conn = null;
  		    PreparedStatement stmt = null;
  		    String sql = null;
  		    
			//Differenciates the Teacher and Student views
			if(user.equals("STUDENT"))
			{	
				// STUDENT VIEW
				
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t<!-- /////////// MODAL TO JOIN CLASS \\\\\\\\\\\\\\\\\\\\\\\\ --> \r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t\t\t\t\t  <!-- Trigger the modal with a button -->\r\n");
      out.write("\t\t\t\t\t\t\t  <h4 class =\"col-sm-10\"><b>Your Classes</b></h4>\r\n");
      out.write("\t\t\t\t\t\t\t  <button type=\"button\" class=\"btn btn-info btn-md col-sm-2\" data-toggle=\"modal\" data-target=\"#myModal\">Join Class</button>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t  <!-- Modal -->\r\n");
      out.write("\t\t\t\t\t\t\t  <div class=\"modal fade\" id=\"myModal\" role=\"dialog\">\r\n");
      out.write("\t\t\t\t\t\t\t    <div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t\t\t\t\t    \r\n");
      out.write("\t\t\t\t\t\t\t      <!-- Modal content-->\r\n");
      out.write("\t\t\t\t\t\t\t      <div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t\t\t        <div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t\t          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t\t\t\t\t\t\t          <h4 class=\"modal-title\">Join Class</h4>\r\n");
      out.write("\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t        <div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t\t         \t\t<!-- FORM FOR CREATING CLASS -->\r\n");
      out.write("\t\t\t\t\t\t\t         \t\t<form class=\"form-horizontal\" role=\"form\" action=\"joinclass.jsp\" method=\"POST\">\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      <label class=\"control-label col-sm-2\" >Class Name:</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      <div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t        <input type=\"text\" class=\"form-control\" name=\"classname\" placeholder=\"Enter Subject\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      <label class=\"control-label col-sm-2\" for=\"pwd\">Pass Key:</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      <div class=\"col-sm-10\">          \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t        <input type=\"password\" class=\"form-control\" name=\"password\" placeholder=\"Enter password\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <div class=\"form-group\">        \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      <div class=\"col-sm-offset-2 col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t        <button type=\"submit\" class=\"btn btn-default\">Submit</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t  </form>\r\n");
      out.write("\t\t\t\t\t\t\t         \t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t        <div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t          <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t\t\t      \r\n");
      out.write("\t\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- /////////// Displays All Of His Classes\\\\\\\\\\\\\\\\\\\\\\ -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \t<div class=\"table-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \t\t<table class=\"table table-striped table-hover\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \t\t\t<thead>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \t\t\t\t<th> Class Name</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \t\t\t\t<th> Attended</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \t\t\t\t<th> View Class</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \t\t\t");
	
									  		
									  		    try{
									  				Class.forName(JDBC_DRIVER);
									  				conn = DriverManager.getConnection(DB_URL, USER, PASS);
									  			
									  				sql = "select classname,classcount,attended from class c,enrolled e where c.class_id=e.c_id and e.s_id = ?;";
									  		    	stmt = conn.prepareStatement(sql);
									  		    	stmt.setString(1,id);
									  		    	ResultSet rs=stmt.executeQuery();
									
									  		    	while(rs.next())
									  		    	{
									  		    		Float percentage = (Float.parseFloat(rs.getString(3))/Float.parseFloat(rs.getString(2)))*100;
									  		    		
									  		    		DecimalFormat form = new DecimalFormat("00.00");
									  		    		
									  		    		out.println("<tr class='active'>");
									  		    		out.println("<td>"+rs.getString(1)+"</td>");
									  		    		out.println("<td>"+String.valueOf(form.format(percentage))+"%"+"  ("+rs.getString(3)+"/"+rs.getString(2)+")"+"</td>");
									  		    		out.println("<td><form action='' method='POST'><button type='submit' class='btn btn-primary'>View <span class='glyphicon glyphicon-stats'></span></button></td>");
									  		    		out.println("</tr>");
									  		    		
									  		    	}
									  		    	
									  		    	
													}catch(SQLException se){
														out.println("Oops : Technical Error , please try again later");
													    se.printStackTrace();
													}catch(Exception e){
														out.println("Oops : Technical Error , please try again later");
													    e.printStackTrace();
													}finally{
													        
														 try{
															 if(conn!=null)
														            conn.close();
													        }catch(SQLException se){
													           se.printStackTrace();
													        }
													}
									  			
									  			
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t</div>\t\t\r\n");
      out.write("\t\t\t\t");

			}
			else if(user.equals("TEACHER"))
			{
				ArrayList<String> classlist = new ArrayList();
				ArrayList<String> idlist = new ArrayList();
				
				// TEACHER VIEW
				
				
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t<!-- /////////// MODAL TO ADD CLASS \\\\\\\\\\\\\\\\\\\\\\\\ --> \r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t\t\t\t\t  <!-- Trigger the modal with a button -->\r\n");
      out.write("\t\t\t\t\t\t\t  <h4 class =\"col-sm-10\"><b>Your Classes</b></h4>\r\n");
      out.write("\t\t\t\t\t\t\t  <button type=\"button\" class=\"btn btn-info btn-md col-sm-2\" data-toggle=\"modal\" data-target=\"#myModal\">Add Class</button>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t  <!-- Modal -->\r\n");
      out.write("\t\t\t\t\t\t\t  <div class=\"modal fade\" id=\"myModal\" role=\"dialog\">\r\n");
      out.write("\t\t\t\t\t\t\t    <div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t\t\t\t\t    \r\n");
      out.write("\t\t\t\t\t\t\t      <!-- Modal content-->\r\n");
      out.write("\t\t\t\t\t\t\t      <div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t\t\t        <div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t\t          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t\t\t\t\t\t\t          <h4 class=\"modal-title\">Add Class</h4>\r\n");
      out.write("\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t        <div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t\t         \t\t<!-- FORM FOR CREATING CLASS -->\r\n");
      out.write("\t\t\t\t\t\t\t         \t\t<form class=\"form-horizontal\" role=\"form\" action=\"createclass.jsp\" method=\"POST\">\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      <label class=\"control-label col-sm-2\" >Subject:</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      <div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t        <input type=\"text\" class=\"form-control\" name=\"subject\" placeholder=\"Enter Subject\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      <label class=\"control-label col-sm-2\">Class Year:</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      <div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t        <input type=\"text\" class=\"form-control\" name=\"year\" placeholder=\"Enter Year\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      <label class=\"control-label col-sm-2\">Class Section:</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      <div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t        <input type=\"text\" class=\"form-control\" name=\"section\" placeholder=\"Enter Section\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      <label class=\"control-label col-sm-2\" for=\"pwd\">Registration Passkey:</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      <div class=\"col-sm-10\">          \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t        <input type=\"password\" class=\"form-control\" name=\"password\" placeholder=\"Enter password\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <div class=\"form-group\">        \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      <div class=\"col-sm-offset-2 col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t        <button type=\"submit\" class=\"btn btn-default\">Submit</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t  </form>\r\n");
      out.write("\t\t\t\t\t\t\t         \t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t        <div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t          <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t\t\t      \r\n");
      out.write("\t\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t<!-- /////////// Displays All Of His Classes\\\\\\\\\\\\\\\\\\\\\\ -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t\t\t\t  <div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t  \t<div class=\"table-responsive\">\r\n");
      out.write("\t\t\t\t\t\t  \t\t<table class=\"table table-striped table-hover\">\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t<thead>\t\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t\t<th> Class Name</th>\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t\t<th> Pass key</th>\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t\t<th> Classes held</th>\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t\t<th> Students Enrolled</th>\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t\t<th> View Class</th>\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t");
	
						  		
						  		    	
						  		    try{
						  				Class.forName(JDBC_DRIVER);
						  				conn = DriverManager.getConnection(DB_URL, USER, PASS);
						  			
						  				sql = "select classname,password,classcount,enrollednumber,class_id from class where t_id = ?";
						  		    	stmt = conn.prepareStatement(sql);
						  		    	stmt.setString(1,id);
						  		    	ResultSet rs=stmt.executeQuery();
						  		    	
						  		    		int count=0;
							  		    	while(rs.next())
							  		    	{	
							  		    		classlist.add(rs.getString(1));
							  		    		idlist.add(rs.getString(5));
							  		    		
							  		    		out.println("<tr class=' active'>");
							  		    		out.println("<td>"+rs.getString(1)+"</td>");
							  		    		out.println("<td>"+rs.getString(2)+"</td>");
							  		    		out.println("<td>"+rs.getString(3)+"</td>");
							  		    		out.println("<td>"+rs.getString(4)+"</td>");
							  		    		out.println("<td>"+"<form action='' method='POST'><button type='submit' class='btn btn-primary'>View <span class='glyphicon glyphicon-stats'></span></button></form>"+"</td>");
							  		    		out.println("</tr>");
							  		    		count++;
							  		    	}
							  		    	if(count==0)
							  		    	{
							  		    		out.println("no classes added");
							  		    	}
						  		    	
										}catch(SQLException se){
											out.println("Oops : Technical Error , please try again later");
										    se.printStackTrace();
										}catch(Exception e){
											out.println("Oops : Technical Error , please try again later");
										    e.printStackTrace();
										}finally{
										        
											 try{
												 if(conn!=null)
											            conn.close();
										        }catch(SQLException se){
										           se.printStackTrace();
										        }
										}
						  			
						  			
      out.write("\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t  \t\t</table>\r\n");
      out.write("\t\t\t\t\t  \t</div>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t</div>\t\t\t\t\t\t  \t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t\t      <div class=\"panel-heading\"><b>Take Attendance</b></div>\r\n");
      out.write("\t\t\t\t      <div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t      \t\t<table class=\"table table-striped table-hover\">\r\n");
      out.write("\t\t\t\t    \t\t\t<thead>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \t\t<th> Class Name</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \t\t<th> Take attendance</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</thead>  \t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 
									for(int i=0;i<classlist.size();i++)
									{
										out.println("<tr>");
											out.println("<td>");
												out.println(classlist.get(i));
											out.println("</td>");

											out.println("<td>");
												out.println("<form action='takeattendance.jsp' method='POST'><input type='hidden' name='class_id' value='"+idlist.get(i)+"'><button type='submit' class='btn btn-primary	'>Take Attendance</button></form>");
											out.println("</td>");
										out.println("</tr>");
									}
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t      \t\t</table>\r\n");
      out.write("\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t");

			}
			
			
		}
		else{
			String redirectURL = "login.jsp";
    	    response.sendRedirect(redirectURL);
			
		}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
