/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2015-12-09 19:25:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Turnout -Login</title>\r\n");
      out.write("\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write(" <!-- Bootstrap -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css\">\r\n");
      out.write("  \t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js\"></script>\r\n");
      out.write(" \t<script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js\"></script>\r\n");
      out.write("<!-- Style Sheet-->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"MainStyle.css\">\r\n");
      out.write("\t\r\n");
      out.write("</head>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<nav class=\"navbar navbar-inverse\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <div class=\"navbar-header\">\r\n");
      out.write("      <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#myNavbar\">\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>                        \r\n");
      out.write("      </button>\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"index.jsp\"><span class=\"glyphicon glyphicon-education\"></span><b>&nbspTurnout</b></a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"myNavbar\">\r\n");
      out.write("      <ul class=\"nav navbar-nav\">\r\n");
      out.write("        <li class=\"active\"><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("        <li><a href=\"about.jsp\">About</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("      <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("        <li><a href=\"signup.jsp\"><span class=\"glyphicon glyphicon-user\"></span> Sign Up</a></li>\r\n");
      out.write("         ");
	if(session.getAttribute("ID")==null)
        		{	
        			
      out.write("\r\n");
      out.write("        \t\t\t\t<li><a href=\"login.jsp\"><span class=\"glyphicon glyphicon-log-in\"></span> Login</a></li>\r\n");
      out.write("        \t\t\t");
 
        		}
       		else
       		{
       			
      out.write("\r\n");
      out.write("\t\t\t\t<li><a href=\"logout.jsp\"><span class=\"glyphicon glyphicon-log-in\"></span> Logout</a></li>\r\n");
      out.write("\t\t\t\t");
 
       		}
        
      out.write("\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");

		String usn = request.getParameter("usn");
		String password = request.getParameter("password");
		String email = request.getParameter("email");
		String user = request.getParameter("user");
		
		// JDBC driver name and database URL
		    String JDBC_DRIVER = "com.mysql.jdbc.Driver";  
		    String DB_URL = "jdbc:mysql://www.virtualhighs.com:3306/turnout";
		
		   //  Database credentials
		    String USER = "ateam";
		    String PASS = "1191995";
		
		    Connection conn = null;
		    PreparedStatement stmt = null;
		    String sql = null;
		    
		    if((usn!= null || email!=null) && password!=null)
		    {	
		    	
				    try{
						Class.forName(JDBC_DRIVER);
						conn = DriverManager.getConnection(DB_URL, USER, PASS);
						
						
						if(user.equals("STUDENT"))
						{
								//checking for the excistance of the username
								sql = "select password,s_id from student where usn=?";
						    	stmt = conn.prepareStatement(sql);
						    	stmt.setString(1,usn);
						    	ResultSet rs=stmt.executeQuery();
						    	
						    	if(rs.next())
						    		if(rs.getString("password").equals(password))
						    		{
						    				//out.println("success");
								    		String redirectURL = "index.jsp";
								    	    session.setAttribute("USER",user);
								    	    session.setAttribute("USERNAME",usn);
								    	    session.setAttribute("ID",rs.getString("s_id"));
								    	    response.sendRedirect(redirectURL);
								    	
						    		}
						    		else
						    		{
						    			
      out.write("\r\n");
      out.write("\t\t\t\t\t\t    \t\t\t<script language=\"javascript\">\r\n");
      out.write("\t\t\t\t\t\t    \t\t\talert(\"Incorrect Credential\");\t\r\n");
      out.write("\t\t\t\t\t\t    \t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t    \t\t\t");

						    		}
						    	
						
						   }
						    else if(user.equals("TEACHER")){
						    	


						    	//checking for the excistance of the username
								sql = "select password,t_id from teacher where username=?";
						    	stmt = conn.prepareStatement(sql);
						    	stmt.setString(1,email);
						    	//out.println(stmt);
						    	ResultSet rs=stmt.executeQuery();
						    	
						    	if(rs.next())
						    		if(rs.getString("password").equals(password))
						    		{
							    		String redirectURL = "index.jsp";
							    	    session.setAttribute("USER",user);
							    	    session.setAttribute("USERNAME",email);
							    	    session.setAttribute("ID",rs.getString("t_id"));
							    	    response.sendRedirect(redirectURL);
							    	    
						    		}
						    		else
						    		{
						    			out.println("Oops : Try Again :p");
						    			
						    		}
						    	
								
							
						   }
				    	
				    	
				    }catch(SQLException se){
				    	out.println("Oops : Technical Error , please try again later");
				        se.printStackTrace();
				    }catch(Exception e){
				    	out.println("Oops : Technical Error , please try again later");
				        e.printStackTrace();
				    }finally{
					        
				    	 try{
				    		 if(conn!=null)
				    	            conn.close();
					        }catch(SQLException se){
					           se.printStackTrace();
					        }
				}
}

      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("  <h2>Lets Login now</h2>\r\n");
      out.write("  <ul class=\"nav nav-tabs\">\r\n");
      out.write("    <li class=\"active\"><a data-toggle=\"tab\" href=\"#home\">Teacher</a></li>\r\n");
      out.write("    <li><a data-toggle=\"tab\" href=\"#menu1\">Student</a></li>\r\n");
      out.write("  </ul>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"tab-content\">\r\n");
      out.write("    <div id=\"home\" class=\"tab-pane fade in active\">\r\n");
      out.write("\t      \t<!-- ### TEACHER FORM ### -->\r\n");
      out.write("\t      \t<h3>Teacher</h3>\r\n");
      out.write("\t      \t\r\n");
      out.write("\t      \t<form class=\"form-horizontal\" role=\"form\"  action=\"login.jsp\" method=\"POST\">\r\n");
      out.write("\t\t\t    <div class=\"form-group\">\r\n");
      out.write("\t\t\t      \t  <label class=\"control-label col-sm-2\" for=\"email\">Email:</label>\r\n");
      out.write("\t\t\t\t      <div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t        <input type=\"text\" class=\"form-control\" name=\"email\" placeholder=\"Enter email id\">\r\n");
      out.write("\t\t\t\t      </div>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t    <div class=\"form-group\">\r\n");
      out.write("\t\t\t      \t  <label class=\"control-label col-sm-2\" for=\"pwd\">Password:</label>\r\n");
      out.write("\t\t\t\t      <div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t        <input type=\"password\" class=\"form-control\" name=\"password\" placeholder=\"choose password\">\r\n");
      out.write("\t\t\t\t      </div>\t\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t    <div class=\"form-group\">        \r\n");
      out.write("\t\t\t      <div class=\"col-sm-offset-2 col-sm-10\">\r\n");
      out.write("\t\t\t        <button type=\"submit\" class=\"btn btn-default\">Submit</button>\r\n");
      out.write("\t\t\t      </div>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t    <input type=\"hidden\" name=\"user\" value=\"TEACHER\">\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("    \t \r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"menu1\" class=\"tab-pane fade\">\r\n");
      out.write("\t\t<!-- ### STUDENT FORM ### -->\r\n");
      out.write("      \t<h3>Student</h3>\r\n");
      out.write("      \t<form class=\"form-horizontal\" role=\"form\" action=\"login.jsp\" method=\"POST\">\r\n");
      out.write("\t\t\t    <div class=\"form-group\">\r\n");
      out.write("\t\t\t      \t  <label class=\"control-label col-sm-2\" >USN:</label>\r\n");
      out.write("\t\t\t\t      <div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t        <input type=\"text\" class=\"form-control\" name=\"usn\" placeholder=\"Enter USN\">\r\n");
      out.write("\t\t\t\t      </div>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t    <div class=\"form-group\">\r\n");
      out.write("\t\t\t      \t  <label class=\"control-label col-sm-2\" for=\"pwd\">Password:</label>\r\n");
      out.write("\t\t\t\t      <div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t        <input type=\"password\" class=\"form-control\" name=\"password\" placeholder=\"choose password\">\r\n");
      out.write("\t\t\t\t      </div>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t    <div class=\"form-group\">        \r\n");
      out.write("\t\t\t      <div class=\"col-sm-offset-2 col-sm-10\">\r\n");
      out.write("\t\t\t        <button type=\"submit\" class=\"btn btn-default\">Submit</button>\r\n");
      out.write("\t\t\t      </div>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t     <input type=\"hidden\" name=\"user\" value=\"STUDENT\">\r\n");
      out.write("\t\t</form>\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
