/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2015-12-10 03:14:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class takeattendance_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Turnout -Login</title>\r\n");
      out.write("\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write(" <!-- Bootstrap -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css\">\r\n");
      out.write("  \t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js\"></script>\r\n");
      out.write(" \t<script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js\"></script>\r\n");
      out.write(" \t<link href=\"https://gitcdn.github.io/bootstrap-toggle/2.2.0/css/bootstrap-toggle.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<script src=\"https://gitcdn.github.io/bootstrap-toggle/2.2.0/js/bootstrap-toggle.min.js\"></script>\r\n");
      out.write("<!-- Style Sheet-->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"MainStyle.css\">\r\n");
      out.write("\t\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-inverse\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <div class=\"navbar-header\">\r\n");
      out.write("      <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#myNavbar\">\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>                        \r\n");
      out.write("      </button>\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"index.jsp\"><span class=\"glyphicon glyphicon-education\"></span><b>&nbspTurnout</b></a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"myNavbar\">\r\n");
      out.write("      <ul class=\"nav navbar-nav\">\r\n");
      out.write("        <li class=\"active\"><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("        <li><a href=\"about.jsp\">About</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("      <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("        <li><a href=\"signup.jsp\"><span class=\"glyphicon glyphicon-user\"></span> Sign Up</a></li>\r\n");
      out.write("        ");
	if(session.getAttribute("ID")==null)
        		{	
        			
      out.write("\r\n");
      out.write("        \t\t\t\t<li><a href=\"login.jsp\"><span class=\"glyphicon glyphicon-log-in\"></span> Login</a></li>\r\n");
      out.write("        \t\t\t");
 
        		}
       		else
       		{
       			
      out.write("\r\n");
      out.write("\t\t\t\t<li><a href=\"logout.jsp\"><span class=\"glyphicon glyphicon-log-in\"></span> Logout</a></li>\r\n");
      out.write("\t\t\t\t");
 
       		}
        
      out.write("\r\n");
      out.write("        \r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<form method=\"POST\" action=\"updateattendance.jsp\">\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\t\t\t <div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"table-responsive\">\r\n");
      out.write("\t\t\t  \t\t<table class=\"table table-striped table-hover\">\r\n");
      out.write("\t\t\t\t  \t\t\t<thead>\t\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t\t<th> USN</th>\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t\t<th> Present</th>\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t</tr>\r\n");
      out.write("\t\t\t\t  \t\t\t</thead>\r\n");
      out.write("\t\t  \t\t\t<tbody>\r\n");

	//getting the class id
	String class_id = request.getParameter("class_id");
	
	//getting the session variables(session var map given at the top)
	String user = (String) session.getAttribute("USER");
	String username =(String)  session.getAttribute("USERNAME");
	String id = (String) session.getAttribute("ID");

	// JDBC driver name and database URL
    String JDBC_DRIVER = "com.mysql.jdbc.Driver";  
    String DB_URL = "jdbc:mysql://www.virtualhighs.com:3306/turnout";

   //  Database credentials
    String USER = "ateam";
    String PASS = "1191995";

    Connection conn = null;
    PreparedStatement stmt = null;
    String sql = null;
    
    try{
		Class.forName(JDBC_DRIVER);
		conn = DriverManager.getConnection(DB_URL, USER, PASS);
		

		sql = "insert into recordclass(c_id,date) values("+class_id+",now())";
    	Statement juststmt = conn.createStatement();
  
   		int check = juststmt.executeUpdate(sql,Statement.RETURN_GENERATED_KEYS);
   		
		if(check>0)
    	{	
			//getting the autoincrement id
			int rs_id;
			ResultSet getId = juststmt.getGeneratedKeys();
			if (getId.next()) {
		        rs_id = getId.getInt(1);
		       	
		        out.println("<input type='hidden' name='rs_id' value='"+rs_id+"'>");
		        
		    } else {
				out.println("update error");
		    }

			
			
			sql = "select s_id,usn from student where s_id in ( select s_id from enrolled e where  e.c_id = ?);";
	    	stmt = conn.prepareStatement(sql);
    		stmt.setString(1, class_id);
    		
    		 ResultSet rs = stmt.executeQuery();
	    
			int count=1;    		 	
    		 while(rs.next())
    		 {
    			 out.println("<tr>");
    			 out.println("<td>");
    			 	out.println(rs.getString(2));	
    			 out.println("</td>");	
    			 out.println("<td>");
 			 		out.println("<input type='checkbox' class='collapsed' name='"+rs.getString(1)+"' checked data-toggle='toggle'>");
    			 out.println("</td>");	
    			 out.println("</tr>");
    			 count++;
    			 
    		 }
    	}
		else
		{
		   out.println("<script type=\"text/javascript\">");
			   out.println("alert('Class already exists');");
			   out.println("location='index.jsp';");
			   out.println("</script>");
		}
	 
		
		
    }catch(SQLException se){
    	out.println("Oops : Technical Error , please try again later");
        se.printStackTrace();
    }catch(Exception e){
    	out.println("Oops : Technical Error , please try again later");
        e.printStackTrace();
    }finally{
	        
    	 try{
    		 if(conn!=null)
    	            conn.close();
    		 
    		 
	        }catch(SQLException se){
	           se.printStackTrace();
	        }
}


      out.write("\r\n");
      out.write("\t</tbody>\r\n");
      out.write("</table>\r\n");
      out.write("\t<button type=\"submit\" class=\"btn btn-primary\">Done</button>\r\n");
      out.write("</form>\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\t\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
