/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2015-12-10 03:27:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.Map;
import java.util.Set;
import java.util.Iterator;

public final class updateattendance_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");



	ArrayList<String> attendedlist = new ArrayList();
	
// I made a mistake with the name, ASSUME  rs_id  is synonymous to rc_id 
	String rs_id = request.getParameter("rs_id");
	
	// JDBC driver name and database URL
    String JDBC_DRIVER = "com.mysql.jdbc.Driver";  
    String DB_URL = "jdbc:mysql://www.virtualhighs.com:3306/turnout";

   //  Database credentials
    String USER = "ateam";
    String PASS = "1191995";

    Connection conn = null;
    PreparedStatement stmt = null;
	
	
	
	Map m=request.getParameterMap();
	Set s = m.entrySet();
	Iterator it = s.iterator();
	
	    while(it.hasNext()){
	
	        Map.Entry<String,String[]> entry = (Map.Entry<String,String[]>)it.next();
	
	        String key             = entry.getKey();
	        String [] value         = entry.getValue();
		
	       	if(!key.equals("rs_id"))
	        	attendedlist.add(key);
	    }
	    
	    String sql="insert into record(rc_id,s_id) values";
	    
	    for(int i = 0; i< attendedlist.size();i++)
	    {
	    	if(i!=0)
	    		sql=sql+",";
	    	sql=sql+"("+rs_id+","+attendedlist.get(i)+")";
	    }
	    

	    try{
			Class.forName(JDBC_DRIVER);
			conn = DriverManager.getConnection(DB_URL, USER, PASS);
			
			stmt = conn.prepareStatement(sql);
			int check =stmt.executeUpdate();
			
			if(check>0)
	    	{	
			   out.println("<script type=\"text/javascript\">");
			   out.println("alert('Attendance Updated');");
			   out.println("location='index.jsp';");
			   out.println("</script>");
			}
			else{
				
				   out.println("<script type=\"text/javascript\">");
				   out.println("alert('Update Error: Sorry our minions have failed! try again');");
				   out.println("location='index.jsp';");
				   out.println("</script>");
			}
			
	    }catch(SQLException se){
	    	out.println("Oops : Technical Error , please try again later");
	        se.printStackTrace();
	    }catch(Exception e){
	    	out.println("Oops : Technical Error , please try again later");
	        e.printStackTrace();
	    }finally{
		        
	    	 try{
	    		 if(conn!=null)
	    	            conn.close();
	    		 
	    		 
		        }catch(SQLException se){
		           se.printStackTrace();
		        }
	}


      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
